
---
title: Word gender bias
author: Molly Lewis 
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
    number_sections: no
    toc: yes
---
  
******

```{r setup, include = F}

# load packages
library(knitr)
library(rmarkdown)
library(here)
library(tidyverse)
library(broom)
#library(langcog)


opts_chunk$set(echo = T, message = F, warning = F, 
               error = F, tidy = F, cache = F)
```

```{r}
SCORE_PATH <-here("exploratory_analyses/5_IAT_tests/data/other/by_word_gender_scores.csv")
model_biases <- read_csv(SCORE_PATH, col_names = c("model", "word", "female_target", "male_target", "male_score")) %>%
  mutate(model2 = str_split(model, "_5_count_"),
         corpus = map_chr(model2, ~pluck(.x, 1)),
       #  model_id = map_chr(model2, ~pluck(.x, 2)),
         corpus = case_when(model == "wiki" ~ "wiki", TRUE ~ corpus)) %>%
  select(-model2, -model)


# take average across model runs
model_scores <- model_biases %>%
  group_by(corpus, word) %>%
  summarize(male_score = mean(male_score)) 
```

```{r}
# Merge with human data
GENDER_NORMS <- here("data/processed/words/gender_ratings_mean.csv")

gender_words <- read_csv(GENDER_NORMS)
gender_norms <- gender_words %>%
  mutate(word = map_chr(word, ~unlist(str_split(.x, " "))[[1]]),
         word = tolower(word),
         word = str_remove_all(word, '[:punct:]')) %>%
  distinct(word, .keep_all = T) %>%
  group_by(word) %>%
  summarize(human_gender_rating  = mean(mean, na.rm = T))


all_scores <- gender_norms %>%
  inner_join(model_scores)
```

```{r}
all_scores %>%
  ggplot(aes( x = male_score,
              y = human_gender_rating,
              color = corpus)) +
  geom_point(size = .5, alpha = .2)+
  geom_smooth(method = "lm") +
  theme_classic()

all_scores %>%
  group_by(corpus) %>%
  nest() %>%
  mutate(test = map(data, ~ tidy(cor.test(.x$male_score, 
                                          .x$human_gender_rating)))) %>%
  select(-data) %>%
  unnest()  %>%
  select(1:7) %>%
  mutate(sig = case_when(p.value  < .05  ~ "*", TRUE ~ "")) %>%
  kable()


```

Same words across all models
```{r}

common_words <- count(all_scores, word) %>%
  filter(n == 3) %>%
  pull(word)

all_scores %>%
  filter(word %in% common_words) %>%
  ggplot(aes( x = male_score,
              y = human_gender_rating,
              color = corpus)) +
  geom_point(size = .5, alpha = .2)+
  geom_smooth(method = "lm") +
  theme_classic()
```

```{r}
all_scores %>%
    filter(word %in% common_words) %>%

  group_by(corpus) %>%
  nest() %>%
  mutate(test = map(data, ~ tidy(cor.test(.x$male_score, 
                                          .x$human_gender_rating)))) %>%
  select(-data) %>%
  unnest()  %>%
  select(1:7) %>%
  mutate(sig = case_when(p.value  < .05  ~ "*", TRUE ~ "")) %>%
  kable()
```

Middle range only
```{r}
all_scores %>%
  filter(male_score > -.1, male_score < .1) %>%
  ggplot(aes( x = male_score,
              y = human_gender_rating,
              color = corpus)) +
  geom_point(size = .5, alpha = .2)+
  geom_smooth(method = "lm") +
  theme_classic()

all_scores %>%
  filter(male_score > -.1, male_score < .1) %>%

  group_by(corpus) %>%
  nest() %>%
  mutate(test = map(data, ~ tidy(cor.test(.x$male_score, 
                                          .x$human_gender_rating)))) %>%
  select(-data) %>%
  unnest()  %>%
  select(1:7) %>%
  mutate(sig = case_when(p.value  < .05  ~ "*", TRUE ~ "")) %>%
  kable()
```
