
# Children's Book Corpus
## Method
```{r}
CORPUS_PATH <- here('data/processed/books/tidy_full_corpus_all.csv')
tidy_corpus <- read_csv(CORPUS_PATH) %>%
  filter(!(book_id %in% c("L105", "L112"))) # "Journey" and "Anno's Journey" are pictures books

book_level_descriptives_tokens <- tidy_corpus %>%
  count(book_id)  %>%
  summarize(mean_n = mean(n),
            sd_n = sd(n),
            min_n  = min(n),
            max_n = max(n))

book_level_descriptives_types <- tidy_corpus %>%
  distinct(book_id, word) %>%
  count(book_id) %>%
  summarize(mean_n = mean(n),
            sd_n = sd(n),
            min_n  = min(n),
            max_n = max(n))
```

The Wisconsin Children’s Book Corpus (WCBC) consists of `r length(unique(tidy_corpus$title))`  books marketed for children 5 years old and under. These are books that caregivers commonly read with children; some are also read independently by older children. We selected books from four sources: (1) the top selling books for children in this age range from Amazon.com at the time of collection; (2) titles collected by Hudson Kam and Matthewson (2017) from a survey of Canadian respondents; (3) Time Magazine’s “100 best children’s books of all time” (https://time.com/100-best-childrens-books); and (4) books in the corpus compiled by @montag2015words. The union of these four sets yielded 247 books. The corpus includes the complete text of each book and basic metadata (author, title, etc.). In total, the corpus includes `r format(nrow(tidy_corpus), big.mark = ",")` word tokens (_M_ = `r pull(book_level_descriptives_tokens, mean_n)` per book; min = `r pull(book_level_descriptives_tokens, min_n)`; max = `r format(pull(book_level_descriptives_tokens, max_n), big.mark = ",")`; _SD_ = `r format(round(pull(book_level_descriptives_tokens, sd_n),2), big.mark = ",")`) and `r format(length(unique(tidy_corpus$word)), big.mark = ",")` types (distinct orthographic forms; _M_ = `r pull(book_level_descriptives_types, mean_n)` per book; min = `r pull(book_level_descriptives_types, min_n)`; max = `r format(pull(book_level_descriptives_types, max_n), big.mark = ",")`; _SD_ = `r format(round(pull(book_level_descriptives_types, sd_n),2), big.mark = ",")`). The corpus currently is not publicly available due to copyright issues. 